device : 'cuda'

dataset:
  name : "cifar10"
  batch_size : 64

model: 
  name : "mobilenet_v3_small"
  output_classes : 10

training:
  epochs : 10
  lr : 1e-5
  device : 'cuda'
  verbosity : 10

poison:
  name : "badnets"
  poison_ratio : 0.10
  target_label : 7

  trigger : 

    placement : 
      random : true
      x_loc : 0
      y_loc : 0

    pattern : 
      - [[255,0,0], [255,0,0]]
      - [[255,0,0], [0,0,0]]